## 4.1 基本操作方法

In [1]:
import pandas as pd

### 4.1.1 DataFrame构建及方法

In [4]:
import numpy as np

In [6]:
stock_day_change = np.load('stock_day_change.npy')
stock_day_change.shape

(200, 504)

In [7]:
pd.DataFrame(stock_day_change).head()

,0,1,2,3,4,5,6,7,8,9,...,494,495,496,497,498,499,500,501,502,503
0,-0.014551,0.676743,-0.879165,0.151159,0.234033,2.353558,-0.321865,0.194324,-0.557655,-1.567214,...,1.785020,-1.394752,-0.666963,-0.182328,1.430838,0.740326,0.941221,0.146831,-0.998788,0.409201
1,-1.518723,1.430921,2.514254,0.511472,0.329690,-0.590260,1.065176,0.540790,0.020667,-0.302971,...,-1.089225,0.548362,-0.017192,-0.624215,-0.726609,-1.127301,0.433069,0.087475,-0.475147,0.619932
2,-1.426799,0.302537,-1.624538,-0.342155,-1.530464,-0.753106,-0.552896,-0.666218,-1.414998,-0.885442,...,0.925592,1.011803,0.272902,0.862855,-0.445853,-2.193485,0.325309,-1.820449,0.345738,0.920958
3,0.378241,1.357615,-0.255444,0.667084,-1.041354,0.944126,-0.362219,-0.558194,0.117517,-1.439632,...,0.438583,-2.136676,-1.257067,-0.343405,-1.881026,-0.640978,0.090878,0.712206,1.763552,-0.354058
4,2.051489,-1.523796,1.406298,0.614834,-0.745290,-0.897430,1.609487,-1.162803,1.495119,-0.263125,...,0.144060,1.109635,-0.101013,0.437525,-2.567632,0.381784,-0.726630,-1.529901,0.444213,0.454217

In [8]:
pd.DataFrame(stock_day_change).head(5)

,0,1,2,3,4,5,6,7,8,9,...,494,495,496,497,498,499,500,501,502,503
0,-0.014551,0.676743,-0.879165,0.151159,0.234033,2.353558,-0.321865,0.194324,-0.557655,-1.567214,...,1.785020,-1.394752,-0.666963,-0.182328,1.430838,0.740326,0.941221,0.146831,-0.998788,0.409201
1,-1.518723,1.430921,2.514254,0.511472,0.329690,-0.590260,1.065176,0.540790,0.020667,-0.302971,...,-1.089225,0.548362,-0.017192,-0.624215,-0.726609,-1.127301,0.433069,0.087475,-0.475147,0.619932
2,-1.426799,0.302537,-1.624538,-0.342155,-1.530464,-0.753106,-0.552896,-0.666218,-1.414998,-0.885442,...,0.925592,1.011803,0.272902,0.862855,-0.445853,-2.193485,0.325309,-1.820449,0.345738,0.920958
3,0.378241,1.357615,-0.255444,0.667084,-1.041354,0.944126,-0.362219,-0.558194,0.117517,-1.439632,...,0.438583,-2.136676,-1.257067,-0.343405,-1.881026,-0.640978,0.090878,0.712206,1.763552,-0.354058
4,2.051489,-1.523796,1.406298,0.614834,-0.745290,-0.897430,1.609487,-1.162803,1.495119,-0.263125,...,0.144060,1.109635,-0.101013,0.437525,-2.567632,0.381784,-0.726630,-1.529901,0.444213,0.454217

In [9]:
pd.DataFrame(stock_day_change)[:5]

,0,1,2,3,4,5,6,7,8,9,...,494,495,496,497,498,499,500,501,502,503
0,-0.014551,0.676743,-0.879165,0.151159,0.234033,2.353558,-0.321865,0.194324,-0.557655,-1.567214,...,1.785020,-1.394752,-0.666963,-0.182328,1.430838,0.740326,0.941221,0.146831,-0.998788,0.409201
1,-1.518723,1.430921,2.514254,0.511472,0.329690,-0.590260,1.065176,0.540790,0.020667,-0.302971,...,-1.089225,0.548362,-0.017192,-0.624215,-0.726609,-1.127301,0.433069,0.087475,-0.475147,0.619932
2,-1.426799,0.302537,-1.624538,-0.342155,-1.530464,-0.753106,-0.552896,-0.666218,-1.414998,-0.885442,...,0.925592,1.011803,0.272902,0.862855,-0.445853,-2.193485,0.325309,-1.820449,0.345738,0.920958
3,0.378241,1.357615,-0.255444,0.667084,-1.041354,0.944126,-0.362219,-0.558194,0.117517,-1.439632,...,0.438583,-2.136676,-1.257067,-0.343405,-1.881026,-0.640978,0.090878,0.712206,1.763552,-0.354058
4,2.051489,-1.523796,1.406298,0.614834,-0.745290,-0.897430,1.609487,-1.162803,1.495119,-0.263125,...,0.144060,1.109635,-0.101013,0.437525,-2.567632,0.381784,-0.726630,-1.529901,0.444213,0.454217

# 4.1.2 索引行列序列

In [13]:
# 股票0 -> 股票stock_day_change.shape[0]
stock_symbols = ['股票' + str(x) for x in range(stock_day_change.shape[0])]
# 通过构造直接设置index参数
pd.DataFrame(stock_day_change, index=stock_symbols).head()

,0,1,2,3,4,5,6,7,8,9,...,494,495,496,497,498,499,500,501,502,503
股票0,-0.014551,0.676743,-0.879165,0.151159,0.234033,2.353558,-0.321865,0.194324,-0.557655,-1.567214,...,1.785020,-1.394752,-0.666963,-0.182328,1.430838,0.740326,0.941221,0.146831,-0.998788,0.409201
股票1,-1.518723,1.430921,2.514254,0.511472,0.329690,-0.590260,1.065176,0.540790,0.020667,-0.302971,...,-1.089225,0.548362,-0.017192,-0.624215,-0.726609,-1.127301,0.433069,0.087475,-0.475147,0.619932
股票2,-1.426799,0.302537,-1.624538,-0.342155,-1.530464,-0.753106,-0.552896,-0.666218,-1.414998,-0.885442,...,0.925592,1.011803,0.272902,0.862855,-0.445853,-2.193485,0.325309,-1.820449,0.345738,0.920958
股票3,0.378241,1.357615,-0.255444,0.667084,-1.041354,0.944126,-0.362219,-0.558194,0.117517,-1.439632,...,0.438583,-2.136676,-1.257067,-0.343405,-1.881026,-0.640978,0.090878,0.712206,1.763552,-0.354058
股票4,2.051489,-1.523796,1.406298,0.614834,-0.745290,-0.897430,1.609487,-1.162803,1.495119,-0.263125,...,0.144060,1.109635,-0.101013,0.437525,-2.567632,0.381784,-0.726630,-1.529901,0.444213,0.454217

In [15]:
# 使用pd.date_range()函数生成一组连续的时间序列，传入columns参数
# 从2017-1-1向上时间递进，单位freq='1d'即1天
days = pd.date_range('2017-1-1', periods=stock_day_change.shape[1], freq='1d')
# 股票0 -> 股票stock_day_change.shape[0]
stock_symbols = ['股票' + str(x) for x in range(stock_day_change.shape[0])]
# 分别设置index和columns
df = pd.DataFrame(stock_day_change, index=stock_symbols, columns=days)
df.head()

,2017-01-01,2017-01-02,2017-01-03,2017-01-04,2017-01-05,2017-01-06,2017-01-07,2017-01-08,2017-01-09,2017-01-10,...,2018-05-10,2018-05-11,2018-05-12,2018-05-13,2018-05-14,2018-05-15,2018-05-16,2018-05-17,2018-05-18,2018-05-19
股票0,-0.014551,0.676743,-0.879165,0.151159,0.234033,2.353558,-0.321865,0.194324,-0.557655,-1.567214,...,1.785020,-1.394752,-0.666963,-0.182328,1.430838,0.740326,0.941221,0.146831,-0.998788,0.409201
股票1,-1.518723,1.430921,2.514254,0.511472,0.329690,-0.590260,1.065176,0.540790,0.020667,-0.302971,...,-1.089225,0.548362,-0.017192,-0.624215,-0.726609,-1.127301,0.433069,0.087475,-0.475147,0.619932
股票2,-1.426799,0.302537,-1.624538,-0.342155,-1.530464,-0.753106,-0.552896,-0.666218,-1.414998,-0.885442,...,0.925592,1.011803,0.272902,0.862855,-0.445853,-2.193485,0.325309,-1.820449,0.345738,0.920958
股票3,0.378241,1.357615,-0.255444,0.667084,-1.041354,0.944126,-0.362219,-0.558194,0.117517,-1.439632,...,0.438583,-2.136676,-1.257067,-0.343405,-1.881026,-0.640978,0.090878,0.712206,1.763552,-0.354058
股票4,2.051489,-1.523796,1.406298,0.614834,-0.745290,-0.897430,1.609487,-1.162803,1.495119,-0.263125,...,0.144060,1.109635,-0.101013,0.437525,-2.567632,0.381784,-0.726630,-1.529901,0.444213,0.454217

### 4.1.3 金融时间序列

In [17]:
# df做个转置
df = df.T
df.head()

,股票0,股票1,股票2,股票3,股票4,股票5,股票6,股票7,股票8,股票9,...,股票190,股票191,股票192,股票193,股票194,股票195,股票196,股票197,股票198,股票199
2017-01-01,-0.014551,-1.518723,-1.426799,0.378241,2.051489,-1.316605,-0.790339,0.543834,-0.598791,-0.479297,...,0.368860,0.381360,-1.282017,1.487516,-0.018943,-0.070609,-0.480102,1.167769,-0.283589,-0.815893
2017-01-02,0.676743,1.430921,0.302537,1.357615,-1.523796,0.767282,1.588124,0.484509,1.667889,-0.519452,...,-1.373225,-1.251486,-0.835385,-0.604452,0.988237,1.340181,-0.780150,0.010687,1.452846,0.988073
2017-01-03,-0.879165,2.514254,-1.624538,-0.255444,1.406298,-1.194664,-0.676910,0.267666,-0.418422,0.244084,...,1.255704,-0.292309,0.692179,0.664160,0.751488,-0.489033,1.371507,-0.061587,-0.096831,-2.114758
2017-01-04,0.151159,0.511472,-0.342155,0.667084,0.614834,-0.158982,-0.150700,1.145522,1.442339,-1.426616,...,2.098742,1.462609,-1.931410,-0.028785,0.445738,-1.606100,-1.302402,-0.697534,0.609714,-0.917575
2017-01-05,0.234033,0.329690,-1.530464,-1.041354,-0.745290,-0.743377,-0.131110,-0.095293,0.281637,1.739301,...,-1.949549,0.281156,-1.235785,1.499654,1.745937,-1.135039,-1.317872,-0.204823,-0.878782,0.926894

In [21]:
# 重新采样，以21天为周期，对21天内的时间求平均来重新塑造数据
df_20 = df.resample('21D', how='mean')
df_20.head()

TypeError: resample() got an unexpected keyword argument 'how'

In [22]:
# 重新采样，以21天为周期，对21天内的时间求平均来重新塑造数据
df_20 = df.resample('21D').mean()
df_20.head()

,股票0,股票1,股票2,股票3,股票4,股票5,股票6,股票7,股票8,股票9,...,股票190,股票191,股票192,股票193,股票194,股票195,股票196,股票197,股票198,股票199
2017-01-01,0.043243,-0.081591,-0.354237,-0.023507,0.076130,-0.277651,0.290329,0.092896,-0.053324,0.331059,...,-0.099709,0.002399,-0.187746,0.054232,0.079055,-0.035945,-0.224733,-0.038774,0.426883,0.210996
2017-01-22,-0.320821,0.039483,-0.182769,0.254906,-0.065871,-0.169192,0.116236,-0.243364,-0.027642,-0.276186,...,0.141261,-0.018817,0.135590,0.170375,-0.396941,0.332650,0.051068,-0.008419,-0.169518,-0.264897
2017-02-12,0.180016,-0.493682,0.015637,0.265898,0.020380,0.200783,0.083469,0.515814,0.163376,-0.206820,...,-0.061535,-0.143994,-0.308984,-0.198301,-0.320555,-0.042466,-0.390250,-0.229817,-0.039229,0.342886
2017-03-05,0.055365,0.012603,-0.101476,0.084424,0.035009,0.068938,0.075440,0.251700,0.106002,0.045436,...,-0.170783,-0.011963,-0.093841,0.254497,0.085519,-0.194782,-0.011734,-0.061105,0.236012,0.005522
2017-03-26,-0.154966,-0.292100,-0.000597,-0.267467,0.056720,-0.270431,-0.442915,0.022839,-0.327084,0.240111,...,0.078638,0.016884,-0.314535,-0.029890,-0.092481,-0.087521,0.421213,0.293874,-0.234800,-0.110045

In [19]:
df.resample?